name: ci-cd

on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  check-python:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install build

    - name: Analysing the code with pylint
      run: |
        python -m pip install pylint
        pylint --fail-under=9 --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Analysing the code with mypy
      run: |
        python -m pip install mypy
        mypy src/
    
    - name: Set up environment
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > $HOME/google-credentials.json

    - name: Set environment variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/google-credentials.json" >> $GITHUB_ENV
    
    - name: Run tests
      env:
        EODAG__COP_DATASPACE__AUTH__CREDENTIALS__USERNAME: ${{ secrets.EODAG__COP_DATASPACE__AUTH__CREDENTIALS__USERNAME }}
        EODAG__COP_DATASPACE__AUTH__CREDENTIALS__PASSWORD: ${{ secrets.EODAG__COP_DATASPACE__AUTH__CREDENTIALS__PASSWORD }}      
      run: |
        pip install .[dev]
        python -m unittest discover -s tests

    - name: Build package
      run: |
        pip install build
        python -m build

  # tests:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Python
  #     uses: actions/setup-python@v5
  #     with:
  #       python-version: '3.10'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       pip install .[dev]
  #   - name: Test with unittest
  #     run: |
  #       python -m unittest discover tests/

  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Only runs on main branch
    env:
      IMAGE_NAME: lookpyr
      PROJECT_ID: lookpyrenees
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT }}
        project_id: ${{ env.PROJECT_ID }}
        export_environment_variables: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
