name: ci-cd

on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  check-python:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        pip install build

    - name: Analysing the code with pylint
      run: |
        python -m pip install pylint
        pylint --fail-under=9 --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Analysing the code with mypy
      run: |
        python -m pip install mypy
        mypy src/
    
    - name: Decode and set up Google Cloud credentials
      run: |
        echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}" | base64 -d > $HOME/google-credentials.json

    - name: Set environment variable
      run: echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/google-credentials.json" >> $GITHUB_ENV

    - name: Run tests
      env:
        EODAG__COP_DATASPACE__AUTH__CREDENTIALS__USERNAME: ${{ secrets.EODAG__COP_DATASPACE__AUTH__CREDENTIALS__USERNAME }}
        EODAG__COP_DATASPACE__AUTH__CREDENTIALS__PASSWORD: ${{ secrets.EODAG__COP_DATASPACE__AUTH__CREDENTIALS__PASSWORD }}      
      run: |
        pip install .[dev]
        python -m unittest discover -s tests

    - name: Build package
      run: |
        pip install build
        python -m build