name: ci-cd

on:
  push:
    branches:
    - '*'
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  check-python:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3.1.0

    - name: Set up Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "cdsapi<0.7"
        pip install "rasterio<1.4"
        pip install "rioxarray<0.14"
        pip install build

    - name: Analysing the code with pylint
      run: |
        python -m pip install pylint
        pylint --fail-under=9 --output-format=text $(find -type f -name "*.py" ! -path "**/venv/**")

    - name: Analysing the code with mypy
      run: |
        python -m pip install mypy
        mypy src/

    # - name: Run tests
    #   run: python -m unittest discover -s tests

    - name: Build package
      run: |
        pip install build
        python -m build

  # release-python:

  #   runs-on: ubuntu-latest
  #   if: startsWith(github.ref, 'refs/tags/')
  #   needs: check-python

  #   steps:

  #   - name: Release
  #     uses: softprops/action-gh-release@v0.1.15
  #     if: startsWith(github.ref, 'refs/tags/')
  #     with:
  #       prerelease: false
  #       files: |
  #         dist/LookPyrenees-*.whl
  #         dist/LookPyrenees-*.tar.gz