name: Manual push to Google Artifact Registry

on:
  workflow_dispatch:

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: lookpyr
      PROJECT_ID: lookpyrenees
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/auth@v1
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY}}
        project_id: ${{ env.PROJECT_ID }}
        export_environment_variables: true

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

    - name: Push Docker Image to Artifact Registry
      run: |-
        docker tag $IMAGE_NAME:latest europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push europe-west1-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest